fix cyprest

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -42,12 +42,12 @@ jobs:
 
       - name: Start preview server
         run: |
-          npm run preview &
+          npm run preview -- --port 5173 &
           sleep 5 # Attendre que le serveur démarre
 
       - name: Run Cypress tests
         run: |
-          npm run test:cypress || echo "Cypress tests failed but continuing..."
+          CYPRESS_BASE_URL=http://localhost:5173 npm run test:cypress || echo "Cypress tests failed but continuing..."
           cat coverage/cypress/lcov.info || true
 
       - name: Merge coverage
